import { TableColumns } from "@shared/models/list-table.interface";
import { MenuItems } from "@shared/models/menu-items.interface";
import { SearchOptions } from "@shared/models/search-options.interface";
import { IconsService } from "@shared/services/icons.service";
import { GenericValidators } from "@shared/validators/generic-validators";
import { ExoneracionResponse } from "../../models/exoneracion-response.interface";

const searchOptions: SearchOptions[] = [
  {
    label: "Status",
    value: 1,
    placeholder: "Buscar por Status",
    validation: [GenericValidators.defaultName],
    validation_desc: "Sólo se permite nombres válidos.",
    icon: "icMail",
  },
  {
    label: "Clasificacion Arancelaria",
    value: 2,
    placeholder: "Buscar por Clasificacion Arancelaria",
    validation: [GenericValidators.defaultName],
    validation_desc: "Sólo se permite nombres válidos.",
    icon: "icMail",
  },
  {
    label: "Categoria",
    value: 3,
    placeholder: "Buscar por Categoria",
    validation: [GenericValidators.defaultName],
    validation_desc: "Sólo se permite nombres válidos.",
    icon: "icMail",
  },
  {
    label: "IDTRA",
    value: 4,
    placeholder: "Buscar por IDTRA",
    validation: [GenericValidators.defaultName],
    validation_desc: "Sólo se permite nombres válidos.",
    icon: "icMail",
  },
  {
    label: "Producto",
    value: 5,
    placeholder: "Buscar por Producto",
    validation: [GenericValidators.defaultName],
    validation_desc: "Sólo se permite nombres válidos.",
    icon: "icMail",
  },
  {
    label: "Tipo Exoneracion",
    value: 6,
    placeholder: "Buscar por Tipo Exoneracion",
    validation: [GenericValidators.defaultName],
    validation_desc: "Sólo se permite nombres válidos.",
    icon: "icMail",
  },
  {
    label: "Cliente",
    value: 7,
    placeholder: "Buscar por Cliente",
    validation: [GenericValidators.defaultName],
    validation_desc: "Sólo se permite nombres válidos.",
    icon: "icMail",
  },
];

const menuItems: MenuItems[] = [
  {
    type: "link",
    id: "all",
    icon: IconsService.prototype.getIcon("icViewHeadline"),
    label: "Todos",
  },
  {
    type: "link",
    id: "Activo",
    value: 1,
    icon: IconsService.prototype.getIcon("icLabel"),
    label: "Activo",
    class: {
      icon: "text-green",
    },
  },
  {
    type: "link",
    id: "Inactivo",
    value: 0,
    icon: IconsService.prototype.getIcon("icLabel"),
    label: "Inactivo",
    class: {
      icon: "text-gray",
    },
  },
];

const tableColumns: TableColumns<ExoneracionResponse>[] = [
  {
    label: "IDTRA",
    cssLabel: ["font-bold", "text-sm"],
    property: "idtra",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "text",
    sticky: false,
    sort: true,
    sortProperty: "idtra",
    visible: true,
    download: true,
  },
  {
    label: "CLIENTE",
    cssLabel: ["font-bold", "text-sm"],
    property: "cliente",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "text",
    sticky: false,
    sort: true,
    sortProperty: "cliente",
    visible: true,
    download: true,
  },
  {
    label: "NOMBRE CLIENTE",
    cssLabel: ["font-bold", "text-sm"],
    property: "nombreCliente",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "text",
    sticky: false,
    sort: true,
    sortProperty: "nombreCliente",
    visible: true,
    download: true,
  },
  {
    label: "TIPO EXONERACION",
    cssLabel: ["font-bold", "text-sm"],
    property: "tipoExoneracion",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "text",
    sticky: false,
    sort: true,
    sortProperty: "tipoExoneracion",
    visible: true,
    download: true,
  },
  {
    label: "STATUS",
    cssLabel: ["font-bold", "text-sm"],
    property: "statusExoneracion",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "text",
    sticky: false,
    sort: true,
    sortProperty: "statusExoneracion",
    visible: true,
    download: true,
  },
  {
    label: "PRODUCTO",
    cssLabel: ["font-bold", "text-sm"],
    property: "producto",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "text",
    sticky: false,
    sort: true,
    sortProperty: "producto",
    visible: true,
    download: true,
  },
  {
    label: "CATEGORIA",
    cssLabel: ["font-bold", "text-sm"],
    property: "categoria",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "text",
    sticky: false,
    sort: true,
    sortProperty: "categoria",
    visible: true,
    download: true,
  },
  {
    label: "CLASIFICACION ARANCELARIA",
    cssLabel: ["font-bold", "text-sm"],
    property: "clasificacionArancelaria",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "text",
    sticky: false,
    sort: true,
    sortProperty: "clasificacionArancelaria",
    visible: true,
    download: true,
  },
  {
    label: "# SOLICITUD",
    cssLabel: ["font-bold", "text-sm"],
    property: "numeroSolicitud",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "text",
    sticky: false,
    sort: true,
    sortProperty: "numeroSolicitud",
    visible: true,
    download: true,
  },
  {
    label: "SOLICITUD",
    cssLabel: ["font-bold", "text-sm"],
    property: "solicitud",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "hiperlink",
    sticky: false,
    sort: true,
    sortProperty: "solicitud",
    visible: true,
    download: true,
  },
  {
    label: "# AUTORIZACION",
    cssLabel: ["font-bold", "text-sm"],
    property: "numeroAutorizacion",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "text",
    sticky: false,
    sort: true,
    sortProperty: "numeroAutorizacion",
    visible: true,
    download: true,
  },
  {
    label: "AUTORIZACION",
    cssLabel: ["font-bold", "text-sm"],
    property: "autorizacion",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "hiperlink",
    sticky: false,
    sort: true,
    sortProperty: "autorizacion",
    visible: true,
    download: true,
  },
  {
    label: "DESDE",
    cssLabel: ["font-bold", "text-sm"],
    property: "desde",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "datetime",
    sticky: false,
    sort: true,
    sortProperty: "desde",
    visible: true,
    download: true,
  },
  {
    label: "HASTA",
    cssLabel: ["font-bold", "text-sm"],
    property: "hasta",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "datetime",
    sticky: false,
    sort: true,
    sortProperty: "hasta",
    visible: true,
    download: true,
  },
  {
    label: "DESCRIPCION",
    cssLabel: ["font-bold", "text-sm"],
    property: "descripcion",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "text",
    sticky: false,
    sort: true,
    sortProperty: "descripcion",
    visible: true,
    download: true,
  },
  {
    label: "F. DE CREACIÓN",
    cssLabel: ["font-bold", "text-sm"],
    property: "fechaCreacionAuditoria",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "datetime",
    sticky: false,
    sort: true,
    visible: true,
    download: true,
  },
  {
    label: "ESTADO",
    cssLabel: ["font-bold", "text-sm"],
    property: "estadoExoneracion",
    cssProperty: ["font-semibold", "text-sm", "text-left"],
    type: "badge",
    sticky: false,
    sort: false,
    visible: true,
    download: true,
  },
  {
    label: "",
    cssLabel: [],
    property: "icEdit",
    cssProperty: [],
    type: "icon",
    action: "edit",
    sticky: false,
    sort: false,
    visible: true,
    download: false,
  },
  {
    label: "",
    cssLabel: [],
    property: "icDelete",
    cssProperty: [],
    type: "icon",
    action: "remove",
    sticky: false,
    sort: false,
    visible: true,
    download: false,
  },
];

const filters = {
  numFilter: 0,
  textFilter: "",
  stateFilter: null,
  startDate: "",
  endDate: "",
  Exoneracion: "",
  refresh: false,
};

const resetFilters = {
  numFilter: 0,
  textFilter: "",
  stateFilter: null,
  startDate: "",
  endDate: "",
  refresh: false,
};

const getInputs: string = "";

export const componentSettings = {
  icClient: IconsService.prototype.getIcon("icExoneracion"),
  searchOptions,
  menuItems,
  tableColumns,
  initialSort: "Id",
  initialSortDir: "desc",
  filters,
  resetFilters,
  getInputs,
  filename: "listado-de-Exoneracion",
};
